### ISSUE TITLE
config file synchronization

### ISSUE THREAD

**Issue by mainjzb** [TheWinds/devgo#6]
A new feature is needed:  config file synchronization
Just need read config file periodically from github or other static pages. This allows developers not to worry about uploading.
Maybe it's very useful when teachers give out common orders to students. Students don't need to edit the config file.
Or you share config file URL to your friends, they just need a little modification.

### Possible implementation

for teacher student mode: 
set sync url: `dg remote https://raw.githubusercontent.com/TheWinds/devgo/main/config/config.toml`
need manual update sync file:  `dg update`

for friends mode:
download config file overlay local file:
`dg get https://raw.githubusercontent.com/TheWinds/devgo/main/config/config.toml`

**Comment by TheWinds** [comment]
I think you can implement this feature by dg itself.

for example,add a config item to update config
```toml
[[group.item]]
title="sync config"
exec="curl -o $HOME/.devgo.toml https://raw.githubusercontent.com/TheWinds/devgo/main/config/config.toml"
```

and we can also add this config item to the default config template for the first time use.
